### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by danvass** [xeodou/react-native-player#4]
Is there any plan to support iOS?

**Comment by xeodou** [comment]
Hi @DVassilev Maybe you can use https://github.com/jsierles/react-native-audio this instead.

**Comment by Partysun** [comment]
@xeodou react-native-audio doesn't support url link for resource.

**Comment by donedgardo** [comment]
@Partysun https://github.com/pwbrown/react-native-ios-network-audio

**Comment by xeodou** [comment]
@donedgardo Cool, I will close this issue now.
